import { MappingGroupHT } from "@/types/mapping-information";

export const BANKS: {
    code: string;
    name: string;
    value: Record<string, string>;
}[] = [
    {
        code: "VCB",
        name: "Vietcombank",
        value: {
            "Account ID *": "[B4]",
            "Date [Header] *": "[A11]",
            "Opening balance amount *": "[D10]",
            "Account Currency *": "[B7]",
            "Statement ID *": "[B4]",
            "Internal Bank Transaction Code": "",
            "Debit Amount *": "[C11]",
            "Credit Amount *": "[D11]",
            "Description": "[E11]",
            "Reference": "[B11]",
            "Transaction Original Amount": "",
            "Transaction Original Amount Currency": "",
        },
    },
    {
        code: "SCB",
        name: "Siam Commercial Bank",
        value: {
            "Account ID *": "[A2]",
            "Date [Header] *": "[B1]",
            "Opening balance amount *": "",
            "Account Currency *": "THB",
            "Statement ID *": "[A2]",
            "Internal Bank Transaction Code": "",
            "Debit Amount *": "[G1]",
            "Credit Amount *": "[H1]",
            "Description": "[K1]",
            "Reference": "",
            "Transaction Original Amount": "",
            "Transaction Original Amount Currency": "",
        },
    },
    {
        code: "BBL",
        name: "Bangkok Bank",
        value: {
            "Account ID *": "[G3]",
            "Date [Header] *": "[A5]",
            "Opening balance amount *": "[Q7]",
            "Account Currency *": "THB",
            "Statement ID *": "[G3]",
            "Internal Bank Transaction Code": "",
            "Debit Amount *": "[L5]",
            "Credit Amount *": "[N5]",
            "Description": "[E5]",
            "Reference": "",
            "Transaction Original Amount": "",
            "Transaction Original Amount Currency": "",
        },
    },
    {
        code: "CTI",
        name: "Citibank",
        value: {
            "Account ID *": "[A10]",
            "Date [Header] *": "[D9]",
            "Opening balance amount *": "",
            "Account Currency *": "[E10]",
            "Statement ID *": "[A10]",
            "Internal Bank Transaction Code": "",
            "Debit Amount *": "[F9]",
            "Credit Amount *": "[F9]",
            "Description": "",
            "Reference": "",
            "Transaction Original Amount": "",
            "Transaction Original Amount Currency": "",
        },
    },
    {
        code: "KBANK",
        name: "Kasikornbank",
        value: {
            "Account ID *": "",
            "Date [Header] *": "[A1]",
            "Opening balance amount *": "",
            "Account Currency *": "[I2]",
            "Statement ID *": "",
            "Internal Bank Transaction Code": "",
            "Debit Amount *": "[E1]",
            "Credit Amount *": "[F1]",
            "Description": "[C1]",
            "Reference": "",
            "Transaction Original Amount": "",
            "Transaction Original Amount Currency": "",
        },
    },
    {
        code: "KTB",
        name: "Krung Thai Bank",
        value: {
            "Account ID *": "[B6]",
            "Date [Header] *": "[A1]",
            "Opening balance amount *": "",
            "Account Currency *": "[D6]",
            "Statement ID *": "[B6]",
            "Internal Bank Transaction Code": "",
            "Debit Amount *": "[F11]",
            "Credit Amount *": "[F11]",
            "Description": "[D11]",
            "Reference": "",
            "Transaction Original Amount": "",
            "Transaction Original Amount Currency": "",
        },
    },
    {
        code: "SIC",
        name: "Siam Commercial Bank (SCB)",
        value: {
            "Account ID *": "[A2]",
            "Date [Header] *": "[B1]",
            "Opening balance amount *": "",
            "Account Currency *": "",
            "Statement ID *": "[A2]",
            "Internal Bank Transaction Code": "",
            "Debit Amount *": "[G1]",
            "Credit Amount *": "[H1]",
            "Description": "[K1]",
            "Reference": "",
            "Transaction Original Amount": "",
            "Transaction Original Amount Currency": "",
        },
    },
    {
        code: "VTB",
        name: "VietinBank",
        value: {
            "Account ID *": "[C12]",
            "Date [Header] *": "[B25]",
            "Opening balance amount *": "[C17]",
            "Account Currency *": "[C14]",
            "Statement ID *": "[C12]",
            "Internal Bank Transaction Code": "",
            "Debit Amount *": "[D25]",
            "Credit Amount *": "[E25]",
            "Description": "[C25]",
            "Reference": "",
            "Transaction Original Amount": "",
            "Transaction Original Amount Currency": "",
        },
    },
] as const;
